// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWMOtyG52ITtHaPHSBPkMq4t3mZeuoUY',
    appId: '1:155331183026:web:61bb556ee36a942061e4ab',
    messagingSenderId: '155331183026',
    projectId: 'flutter-study-84432',
    authDomain: 'flutter-study-84432.firebaseapp.com',
    storageBucket: 'flutter-study-84432.appspot.com',
    measurementId: 'G-TNQK7271JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC03rhcfm_S9YlNMBoiUvPwFr6R_U1PtM',
    appId: '1:155331183026:android:45a59245e8bb6aea61e4ab',
    messagingSenderId: '155331183026',
    projectId: 'flutter-study-84432',
    storageBucket: 'flutter-study-84432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASm83zSZYGaYxpG37rPmAtEpvXu43UFlo',
    appId: '1:155331183026:ios:c9cc8f344008df0861e4ab',
    messagingSenderId: '155331183026',
    projectId: 'flutter-study-84432',
    storageBucket: 'flutter-study-84432.appspot.com',
    iosClientId: '155331183026-u29i97t576r6evq8se6jnuscqrqi210i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASm83zSZYGaYxpG37rPmAtEpvXu43UFlo',
    appId: '1:155331183026:ios:c9cc8f344008df0861e4ab',
    messagingSenderId: '155331183026',
    projectId: 'flutter-study-84432',
    storageBucket: 'flutter-study-84432.appspot.com',
    iosClientId: '155331183026-u29i97t576r6evq8se6jnuscqrqi210i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudy',
  );
}
